<?php

namespace Tests\Browser;

use Tests\DuskTestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class CrudAppointmentTest extends DuskTestCase
{
    /**
     * A Dusk test example.
     *
     * @return void
     */
    public function testGeneric()
    {
        $this->browse(function ($browser) {

            $unique_moment_specialty = date('ymdhis');
            $unique_moment_treatment = date('ymdhis');

            $browser->visit('/')
                    ->assertSee('Iniciar sesión')
                    ->type('#email', 'pablo.fumarola@gmail.com')
                    ->type('#password', '123456')
                    ->click('button.btn')

            // Appointments        
                    ->visit('/#/appointments')
                    ->waitForText('Turnos')
                    ->click('.new-appointment')
                    ->pause(200)
                    ->type('#title', 'Turno urgente')
                    ->click('#date')
                    ->click('.cell.day.selected.highlighted.today')
                    ->type('#hour', '19:00')
                    ->select('#professional_id', \App\Professional::first()->id)
                    ->select('#patient_id', \App\Patient::first()->id)
                    ->select('#specialty_id', 2)
                    ->select('#treatment_id', 2)
                    ->select('#series_id', 2)
                    ->click('#submit-form')
                    ->waitForText('correctamente')
                    ->type('input', 'Turno urgente')
                    ->pause(1000)
                    ->mouseover('.list-item')
                    ->click('.three-buttons a')
                    ->waitForText('Turno urgente')
                    ->clickLink('edit')
                    ->waitForText('Turno urgente')
                    ->type('#title', 'Turno no tan urgente')
                    ->click('#submit-form')
                    ->waitForText('Turno no tan urgente')
                    ->pause(500)
                    ->clickLink('chevron_left')
                    ->type('input', 'Turno no tan urgente')
                    ->pause(1000)
                    ->click('.three-buttons button')
                    ->pause(500)
                    ->click('.modal-footer .error')
                    
            // Patients
                    ->visit('/#/patients')
                    ->waitForText('Pacientes')
                    ->pause(200)
                    ->click('.new-patient')
                    ->pause(200)
                    ->type('#email', 'pacientenuevo' . date('ymdhis') . '@gmail.com')
                    ->type('#cellphone', '541168908443')
                    ->type('#tel', '541168908443')
                    ->type('#dni', '34539064')
                    ->select('#civil_status_id', 2)
                    ->select('#gender_id', 2)
                    ->type('#address', 'Posta de Pardo 123')
                    ->type('#area', 'CABA')
                    ->type('#facebook', 'pacientenuevo123')
                    ->type('#name', 'Paciente nuevo')
                    ->click('#submit-form')
                    ->waitForText('correctamente')
                    ->type('input', 'Paciente nuevo')
                    ->pause(1000)
                    ->mouseover('.list-item')
                    ->click('.three-buttons a')
                    ->waitForText('Paciente nuevo')
                    ->clickLink('edit')
                    ->waitForText('Paciente nuevo')
                    ->type('#name', 'Paciente no tan nuevo')
                    ->click('#submit-form')
                    ->waitForText('Paciente no tan nuevo')
                    ->pause(500)
                    ->clickLink('chevron_left')
                    ->type('input', 'Paciente no tan nuevo')
                    ->pause(1000)
                    ->click('.three-buttons button')
                    ->pause(500)
                    ->click('.modal-footer .error')
                    ->waitForText('correctamente')

            // Professionals
                    ->visit('/#/professionals')
                    ->waitForText('Profesionales')
                    ->click('.new-professional')
                    ->pause(200)
                    ->type('#name', 'Profesional nuevo')
                    ->type('#email', 'profesionalnuevo' . date('ymdhis') . '@gmail.com')
                    ->type('#tel', '541168908443')
                    ->select('#gender_id', 2)
                    ->type('#address', 'Posta de Pardo 123')
                    ->click('#submit-form')
                    ->waitForText('correctamente')
                    ->type('input', 'Profesional nuevo')
                    ->pause(1000)
                    ->mouseover('.list-item')
                    ->click('.three-buttons a')
                    ->waitForText('Profesional nuevo')
                    ->clickLink('edit')
                    ->waitForText('Profesional nuevo')
                    ->type('#name', 'Profesional no tan nuevo')
                    ->click('#submit-form')
                    ->waitForText('Profesional no tan nuevo')
                    ->pause(500)
                    ->clickLink('chevron_left')
                    ->type('input', 'Profesional no tan nuevo')
                    ->pause(1000)
                    ->click('.three-buttons button')
                    ->pause(500)
                    ->click('.modal-footer .error')
                    ->waitForText('correctamente')

            // Series
                    ->visit('/#/series')
                    ->waitForText('Promociones')
                    ->click('.new-series')
                    ->pause(200)
                    ->type('#series', 'Promoción nueva')
                    ->type('#cant', 2)
                    ->click('#submit-form')
                    ->waitForText('correctamente')
                    ->type('input', 'Promoción nueva')
                    ->pause(1000)
                    ->mouseover('.list-item')
                    ->click('.three-buttons a')
                    ->waitForText('Promoción nueva')
                    ->clickLink('edit')
                    ->waitForText('Promoción nueva')
                    ->type('#series', 'Promoción no tan nueva')
                    ->click('#submit-form')
                    ->waitForText('Promoción no tan nueva')
                    ->pause(500)
                    ->clickLink('chevron_left')
                    ->type('input', 'Promoción no tan nueva')
                    ->pause(1000)
                    ->click('.three-buttons button')
                    ->pause(500)
                    ->click('.modal-footer .error')
                    ->waitForText('correctamente')

            // Specialties
                    ->visit('/#/specialties')
                    ->waitForText('Especialidades')
                    ->click('.new-specialty')
                    ->pause(200)
                    ->type('#specialty', 'Especialidad nueva (#' . $unique_moment_specialty . ')')
                    ->type('#description', 'Esta es una nueva especialidad')
                    ->click('#submit-form')
                    ->waitForText('correctamente')
                    ->type('input', 'Especialidad nueva (#' . $unique_moment_specialty . ')')
                    ->pause(1000)
                    ->mouseover('.list-item')
                    ->click('.three-buttons a')
                    ->waitForText('Especialidad nueva (#' . $unique_moment_specialty . ')')
                    ->clickLink('edit')
                    ->waitForText('Especialidad nueva (#' . $unique_moment_specialty . ')')
                    ->type('#specialty', 'Especialidad no tan nueva (#' . $unique_moment_specialty . ')')
                    ->click('#submit-form')
                    ->waitForText('Especialidad no tan nueva (#' . $unique_moment_specialty . ')')
                    ->pause(500)
                    ->clickLink('chevron_left')
                    ->type('input', 'Especialidad no tan nueva (#' . $unique_moment_specialty . ')')
                    ->pause(1000)
                    ->click('.three-buttons button')
                    ->pause(500)
                    ->click('.modal-footer .error')
                    ->waitForText('correctamente')
            
            // Treatments
                    ->visit('/#/treatments')
                    ->waitForText('Tratamientos')
                    ->click('.new-treatment')
                    ->pause(200)
                    ->type('#treatment', 'Tratamiento nuevo (#' . $unique_moment_treatment . ')')
                    ->select('#specialty_id', 2)
                    ->type('#description', 'Esta es una descripción de una tratamiento nuevo')
                    ->click('#submit-form')
                    ->waitForText('correctamente')
                    ->type('input', 'Tratamiento nuevo (#' . $unique_moment_treatment . ')')
                    ->pause(1000)
                    ->mouseover('.list-item')
                    ->click('.three-buttons a')
                    ->waitForText('Tratamiento nuevo (#' . $unique_moment_treatment . ')')
                    ->clickLink('edit')
                    ->waitForText('Tratamiento nuevo (#' . $unique_moment_treatment . ')')
                    ->type('#treatment', 'Tratamiento no tan (#' . $unique_moment_treatment . ')')
                    ->click('#submit-form')
                    ->waitForText('Tratamiento no tan (#' . $unique_moment_treatment . ')')
                    ->pause(500)
                    ->clickLink('chevron_left')
                    ->type('input', 'Tratamiento no tan (#' . $unique_moment_treatment . ')')
                    ->pause(1000)
                    ->click('.three-buttons button')
                    ->pause(500)
                    ->click('.modal-footer .error')
                    ->waitForText('correctamente')

               // Questions
                    ->visit('/#/questions')
                    ->waitForText('Preguntas')
                    ->click('.new-question')
                    ->pause(200)
                    ->type('#question', 'Pregunta nueva')
                    ->select('#specialty_id', 2)
                    ->click('#submit-form')
                    ->waitForText('correctamente')
                    ->type('input', 'Pregunta nueva')
                    ->pause(1000)
                    ->mouseover('.list-item')
                    ->click('.three-buttons a')
                    ->waitForText('Pregunta nueva')
                    ->type('#question', 'Pregunta no tan nueva')
                    ->click('#submit-form')
                    ->pause(500)
                    ->type('input', 'Pregunta no tan nueva')
                    ->pause(1000)
                    ->click('.three-buttons button')
                    ->pause(500)
                    ->click('.modal-footer .error')
                    ->waitForText('correctamente')
            ;
        });
    }
}